apiVersion: v1
kind: Pod
metadata:
  name: backup-restore-tools
  namespace: artifactory
spec:
  containers:
  - name: toolbox
    image: registry1.dso.mil/ironbank/big-bang/base:2.0.0
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: artifactory
      mountPath: /mounts/artifactory
    - name: backup-restore-workspace
      mountPath: /mounts/workspace
    securityContext:
      runAsUser: 1030
  volumes:
  - name: artifactory
    persistentVolumeClaim:
      claimName: artifactory-volume-artifactory-0
  - name: backup-restore-workspace
    persistentVolumeClaim:
      claimName: backup-restore-workspace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-restore-workspace
  namespace: artifactory
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  # storageClassName: ""
