# ENCRYPT THIS FILE!!! DON'T COMMIT IT TO THE REPO UNENCRYPTED! IT CONTAINS SECRETS!!!
resources:
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: new-redis-secret
    stringData:
      secret: "changemechangeme"