# nonk8s
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server-istio-updates
  namespace: bigbang
spec:
  targetNamespace: metrics-server
  releaseName: metrics-server-istio-updates
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: charts/raw
      sourceRef:
        kind: GitRepository
        name: zarf-package-software-factory
        namespace: flux-system
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  dependsOn:
    - name: bigbang
      namespace: bigbang
  values:
    resources:
      - apiVersion: "networking.istio.io/v1alpha3"
        kind: "DestinationRule"
        metadata:
          name: "enable-mtls"
          namespace: "metrics-server"
        spec:
          host: "*.metrics-server.svc.cluster.local"
          trafficPolicy:
            tls:
              mode: ISTIO_MUTUAL
