# nonk8s
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube-istio-updates
  namespace: bigbang
spec:
  targetNamespace: sonarqube
  releaseName: sonarqube-istio-updates
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: charts/raw
      sourceRef:
        kind: GitRepository
        name: zarf-package-software-factory
        namespace: flux-system
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  dependsOn:
    - name: bigbang
      namespace: bigbang
  values:
    resources:
      - apiVersion: "security.istio.io/v1beta1"
        kind: PeerAuthentication
        metadata:
          name: sonarqube-postgresql-exception
          namespace: sonarqube
        spec:
          mtls:
            mode: STRICT
          selector:
            matchLabels:
              cluster-name: acid-sonarqube
          portLevelMtls:
            "5432":
              mode: PERMISSIVE
      - apiVersion: "networking.istio.io/v1alpha3"
        kind: "DestinationRule"
        metadata:
          name: "enable-mtls"
          namespace: "sonarqube"
        spec:
          host: "*.sonarqube.svc.cluster.local"
          trafficPolicy:
            tls:
              mode: ISTIO_MUTUAL
