run:
  timeout: 5m
  skip-files:
    - src/internal/message/logo.go
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - goerr113
    - gofumpt
    - lll
    - stylecheck
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
issues:
  exclude-use-default: false
