run:
  timeout: 5m
  skip-files:
    - src/internal/message/logo.go
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - goerr113
    #   - gofumpt
    - lll
    - stylecheck
    #   - testpackage
    - varnamelen
    #   - wrapcheck
    - wsl
linters-settings:
  funlen:
    lines: 100
issues:
  exclude-use-default: false
