apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: softwarefactoryaddons
spec:
  targetNamespace: postgres-operator
  releaseName: postgres-operator
  interval: 2m
  chart:
    spec:
      interval: 1m
      chart: charts/postgres-operator
      sourceRef:
        kind: GitRepository
        name: postgres-operator
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 30m
    cleanupOnFail: false
  valuesFrom:
    - kind: Secret
      name: postgres-operator-common-bb
      valuesKey: values.yaml
    - kind: ConfigMap
      name: postgres-operator-common
      valuesKey: values.yaml
    - kind: Secret
      name: postgres-operator-environment-bb
      valuesKey: values.yaml
    - kind: ConfigMap
      name: postgres-operator-environment
      valuesKey: values.yaml
  dependsOn:
    - name: istio
      namespace: bigbang
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator-ui
  namespace: softwarefactoryaddons
spec:
  targetNamespace: postgres-operator
  releaseName: postgres-operator-ui
  interval: 2m
  chart:
    spec:
      interval: 1m
      chart: charts/postgres-operator-ui
      sourceRef:
        kind: GitRepository
        name: postgres-operator
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 30m
    cleanupOnFail: false
  valuesFrom:
    - kind: Secret
      name: postgres-operator-ui-common-bb
      valuesKey: values.yaml
    - kind: ConfigMap
      name: postgres-operator-ui-common
      valuesKey: values.yaml
    - kind: Secret
      name: postgres-operator-ui-environment-bb
      valuesKey: values.yaml
    - kind: ConfigMap
      name: postgres-operator-ui-environment
      valuesKey: values.yaml
  dependsOn:
    - name: istio
      namespace: bigbang
