apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: postgres-operator
  namespace: softwarefactoryaddons
spec:
  interval: 5m
  url: https://github.com/zalando/postgres-operator.git
  ref:
    tag: v1.8.2
  secretRef:
    name: private-git-server
