configurations:
  - transformer.yaml

commonLabels:
  owner: softwarefactoryaddons

resources:
  - gitrepository.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: postgres-operator-common
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: postgres-operator-environment
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: postgres-operator-ui-common
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: postgres-operator-ui-environment
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=

# Flux combines secrets and configmaps in `valuesFrom`.  Kustomize
# cannot distinguish between them when applying suffixes.  Therefore,
# the secrets must have different names than the configmaps
# While capital letters or dashes could be used, '-bb' was chosen
# to make the difference obvious at a glance
secretGenerator:
  - name: postgres-operator-common-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: postgres-operator-environment-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: postgres-operator-ui-common-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: postgres-operator-ui-environment-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
