resources:
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    metadata:
      name: minio
    spec:
      interval: 2m
      timeout: 60s
      url: https://repo1.dso.mil/big-bang/product/packages/minio.git
      ref:
        tag: 5.0.3-bb.2
      secretRef:
        name: private-git-server
