tenant:
  # Pre-create buckets that will be needed for various services that will use MinIO
  # NOTE: Region is meaningless in this instantiation of MinIO. It's a required field but the value could be just about anything and it would work fine.
  buckets:
    # loki-logs
    - name: "loki-logs"
      region: "us-east-1"
      objectLock: true
    - name: "loki-ruler"
      region: "us-east-1"
      objectLock: true
    - name: "loki-admin"
      region: "us-east-1"
      objectLock: true
