resources:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: minio-allow-api-ingress
    spec:
      ingress:
        - from:
            - namespaceSelector: {}
          ports:
            - port: 9000
              protocol: TCP
      podSelector: {}
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: minio-allow-in-ns
    spec:
      podSelector: {}
      policyTypes:
        - Ingress
        - Egress
      ingress:
        - from:
            - podSelector: {}
      egress:
        - to:
            - podSelector: {}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: minio-allow-istio-egress
    spec:
      podSelector: {}
      policyTypes:
        - Egress
      egress:
        - to:
            - namespaceSelector:
                matchLabels:
                  app.kubernetes.io/name: istio-controlplane
              podSelector:
                matchLabels:
                  app: istiod
          ports:
            - port: 15012
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: minio-allow-istio-ingress
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  app.kubernetes.io/name: istio-controlplane
              podSelector:
                matchLabels:
                  app: public-ingressgateway
          ports:
            - port: 9090
              protocol: TCP
      podSelector: {}
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: minio-allow-scraping
    spec:
      podSelector: {}
      policyTypes:
        - Ingress
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  app.kubernetes.io/name: monitoring
          ports:
            - port: 9000
              protocol: TCP
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: minio-allow-sidecar-scraping
    spec:
      podSelector: {}
      policyTypes:
        - Ingress
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  app.kubernetes.io/name: monitoring
              podSelector:
                matchLabels:
                  app: prometheus
          ports:
            - protocol: TCP
              port: 15090
            - protocol: TCP
              port: 15020
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: minio-allow-minio-operator-egress
    spec:
      podSelector: {}
      policyTypes:
        - Egress
      egress:
        - to:
            - namespaceSelector:
                matchLabels:
                  app.kubernetes.io/name: minioOperator
          ports:
            - port: 4222
              protocol: TCP
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: minio-allow-to-istio-ingressgateway
    spec:
      podSelector: {}
      policyTypes:
        - Ingress
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  app.kubernetes.io/name: istio-controlplane
              podSelector:
                matchLabels:
                  app: public-ingressgateway
