resources:
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    metadata:
      name: minio
    spec:
      interval: 2m
      timeout: 60s
      url: https://repo1.dso.mil/platform-one/big-bang/apps/application-utilities/minio.git
      ref:
        tag: 4.5.8-bb.0
      secretRef:
        name: private-git-server
