apiVersion: v1
kind: ConfigMap
metadata:
  name: external-sonarqube-opts
  namespace: bigbang
data:
  SONARQUBE_JDBC_USERNAME: postgres
  SONARQUBE_JDBC_URL: jdbc:postgresql://acid-sonarqube.sonarqube.svc.cluster.local:5432/sonar
