apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube-database
  namespace: bigbang
spec:
  targetNamespace: sonarqube
  releaseName: sonarqube-database
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: charts/raw
      sourceRef:
        kind: GitRepository
        name: zarf-package-software-factory
        namespace: flux-system
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  dependsOn:
    - name: bigbang
      namespace: bigbang
    - name: postgres-operator
      namespace: softwarefactoryaddons
    - name: kyvernopolicies
      namespace: bigbang
    - name: istio
      namespace: bigbang
  values:
    resources:
      - apiVersion: "networking.k8s.io/v1"
        kind: NetworkPolicy
        metadata:
          name: allow-to-and-from-postgres-operator
        spec:
          ingress:
            - ports:
                - port: 5432
                  protocol: TCP
              from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: postgres-operator
          egress:
            - ports:
                - port: 8080
                  protocol: TCP
              to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: postgres-operator
          podSelector: {}
          policyTypes:
            - Ingress
            - Egress
      - apiVersion: "acid.zalan.do/v1"
        kind: "postgresql"
        metadata:
          name: "acid-sonarqube"
          namespace: "sonarqube"
          labels:
            # Not sure why yet, but sonarqube's database has a lot of problems if it has sidecar injection turned on.
            # acid-sonarqube-1 throws "ERROR: failed to bootstrap from leader 'acid-sonarqube-0'
            # TODO: Figure out why sonarqube's database has problems with sidecar injections and fix it.
            sidecar.istio.io/inject: "false"
        spec:
          teamId: "acid"
          postgresql:
            version: "13"
          numberOfInstances: 3
          volume:
            size: "2Gi"
            # Uncomment this if you want to specify a particular storage class
            # storageClass: "your-storage-class-name-here"
          # enableLogicalBackup: true
          # logicalBackupSchedule: "*/2 * * * *"
          users:
            sonarqube: []
          databases:
            sonarqube: sonarqube
          env:
          - name: WAL_S3_BUCKET
            value: ""
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: "1"
              memory: 2000Mi
      # Create empty secret so that other postgres clusters can use secrets for env
      - apiVersion: v1
        kind: Secret
        metadata:
          name: postgres-minio-creds-env
        type: Opaque
