image:
  repository: "${ZARF_REGISTRY}/ironbank/atlassian/jira-data-center/jira-node"
imagePullSecrets:
  - name: private-registry
ingress:
  nginx: false
proxyName: jira.di2me.com
hostname: di2me.com
istio:
  enabled: true
  gateways:
    - istio-system/public
jira:
  resources:
    container:
      requests:
        cpu: "100m"
        memory: "2Gi"
      limits:
        cpu: "10"
        memory: "4Gi"
  additionalEnvironmentVariables:
    - name: ATL_DB_TYPE
      value: "postgres72"
    - name: ATL_JDBC_URL
      value: "jdbc:postgresql://acid-jira.jira.svc.cluster.local:5432/jira"
    - name: ATL_JDBC_USER
      valueFrom:
        secretKeyRef:
          name: "jira.acid-jira.credentials.postgresql.acid.zalan.do"
          key: "username"
    - name: ATL_JDBC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "jira.acid-jira.credentials.postgresql.acid.zalan.do"
          key: "password"
