image:
  repository: "${ZARF_REGISTRY}/ironbank/atlassian/jira-data-center/jira-node"
imagePullSecrets:
  - name: private-registry
ingress:
  nginx: false
proxyName: jira.di2me.com
hostname: di2me.com
istio:
  enabled: true
  gateways:
    - istio-system/public
jira:
  resources:
    container:
      requests:
        cpu: "100m"
        memory: "2Gi"
      limits:
        cpu: "10"
        memory: "4Gi"
