image:
  repository: "${ZARF_REGISTRY}/ironbank/atlassian/jira-data-center/jira-node"
imagePullSecrets:
  - name: private-registry
ingress:
  nginx: false
proxyName: jira.di2me.com
hostname: di2me.com
istio:
  enabled: true
  gateways:
    - istio-system/public
jira:
  resources:
    container:
      requests:
        cpu: "100m"
        memory: "2Gi"
      limits:
        cpu: "10"
        memory: "4Gi"
  additionalEnvironmentVariables:
    - name: ATL_DB_TYPE
      value: "postgres72"
    - name: ATL_JDBC_URL
      value: "jdbc:postgresql://acid-jira.jira.svc.cluster.local:5432/jira"
    - name: ATL_JDBC_USER
      valueFrom:
        secretKeyRef:
          name: "jira.acid-jira.credentials.postgresql.acid.zalan.do"
          key: "username"
    - name: ATL_JDBC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "jira.acid-jira.credentials.postgresql.acid.zalan.do"
          key: "password"
additionalInitContainers:
  - name: wait-for-database
    image: "${ZARF_REGISTRY}/acid/spilo-13:2.1-p1"
    # command: ["sh", "-c", "sleep 999999"]
    command:
      [
        "sh",
        "-c",
        'for i in {1..120}; do sleep 1; echo "Attempt $${i} to get a clean connection to the database"; if pg_isready -h acid-jira.jira.svc.cluster.local -p 5432 -d jira; then exit 0; fi; done; exit 1',
      ]
