ingress:
  nginx: false
proxyName: jira.bigbang.dev
hostname: bigbang.dev
istio:
  enabled: true
  gateways:
    - istio-system/public
jira:
  resources:
    container:
      requests:
        cpu: "100m"
        memory: "2Gi"
      limits:
        cpu: "10"
        memory: "6Gi"
    jvm:
      maxHeap: "4g"
  additionalEnvironmentVariables:
    - name: ATL_DB_TYPE
      value: "postgres72"
    - name: ATL_DB_DRIVER
      value: "org.postgresql.Driver"
    - name: ATL_JDBC_URL
      value: "jdbc:postgresql://acid-jira.jira.svc.cluster.local:5432/jira"
    - name: ATL_JDBC_USER
      valueFrom:
        secretKeyRef:
          name: "jira.acid-jira.credentials.postgresql.acid.zalan.do"
          key: "username"
    - name: ATL_JDBC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "jira.acid-jira.credentials.postgresql.acid.zalan.do"
          key: "password"
additionalInitContainers:
  - name: wait-for-database
    image: "registry1.dso.mil/ironbank/opensource/kubernetes/kubectl:v1.25.3"
    command:
      [
        "sh",
        "-c",
        "echo 'Waiting for the postgresql db cluster to report ready'; kubectl wait --for=jsonpath='{.status.PostgresClusterStatus}'='Running' -n jira postgresql/acid-jira --timeout=600s",
      ]
volumes:
  localHome:
    persistentVolumeClaim:
      create: true
      # storageClassName: your-storage-class-here
      resources:
        requests:
          storage: 1Gi

  sharedHome:
    customVolume:
      persistentVolumeClaim:
        claimName: jira-shared-home
