apiVersion: v1
kind: Service
metadata:
  name: postgres-operator-ui-zarf-connect
  namespace: postgres-operator
  annotations:
    zarf.dev/connect-description: "Launch the postgres opertor web interface"
  labels:
    zarf.dev/connect-name: postgres-operator-ui
spec:
  selector:
    app.kubernetes.io/instance: zarf-postgres-operator-ui
    app.kubernetes.io/name: postgres-operator-ui
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
