controller:
  disableRememberMe: true
  resources:
    requests:
      cpu: "50m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "8192Mi"
  initContainerResources:
    requests:
      cpu: "50m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "8192Mi"
  installPlugins:
    # Top level plugins are defined in the deployed bigbang chart values https://repo1.dso.mil/big-bang/product/community/jenkins.git
    # Dependencies of the top level plugins need to be specified explicitly or the top level plugins
    # will try to grab the latest versions of them, which will break other dependency trees. It sucks
    # to have to maintain this list, but it is the only way that this author knows for how to make
    # consistently repeatable Jenkins deployments. The list below needs to be updated when ever the list of top level plugins
    # changes.
    # TO UPDATE IT, delete the list below and run the deployment.
    # Run the below command to list all the plugins used in this successful deployment.
    # kubectl exec -it jenkins-0 -n jenkins -c jenkins -- sh -c "cd /var/jenkins_home/plugins && for file in \$(ls | grep -E '\.version_from_image\$'); do prefix=\$(echo \$file | cut -d. -f1); content=\$(cat \$file); echo \"- \${prefix}:\${content}\"; done"
    # Paste the full updated list below to insure consistent deployment.
    - apache-httpcomponents-client-4-api:4.5.14-150.v7a_b_9d17134a_5
    - authentication-tokens:1.53.v1c90fd9191a_b_
    - bouncycastle-api:2.27
    - branch-api:2.1071.v1a_188a_562481
    - caffeine-api:2.9.3-65.v6a_47d0f4d1fe
    - cloudbees-folder:6.815.v0dd5a_cb_40e0e
    - commons-lang3-api:3.12.0-36.vd97de6465d5b_
    - commons-text-api:1.10.0-36.vc008c8fcda_7b_
    - configuration-as-code:1569.vb_72405b_80249
    - credentials-binding:604.vb_64480b_c56ca_
    - credentials:1224.vc23ca_a_9a_2cb_0
    - display-url-api:2.3.7
    - durable-task:504.vb10d1ae5ba2f
    - git-client:4.2.0
    - git:4.13.0
    - instance-identity:142.v04572ca_5b_265
    - ionicons-api:45.vf54fca_5d2154
    - jackson2-api:2.14.2-319.v37853346a_229
    - jakarta-activation-api:2.0.1-3
    - jakarta-mail-api:2.0.1-3
    - javax-activation-api:1.2.0-6
    - jaxb:2.3.8-1
    - kubernetes-client-api:6.4.1-215.v2ed17097a_8e9
    - kubernetes-credentials:0.10.0
    - kubernetes:3896.v19b_160fd9589
    - mailer:448.v5b_97805e3767
    - metrics:4.2.13-420.vea_2f17932dd6
    - mina-sshd-api-common:2.9.2-62.v199162f0a_2f8
    - mina-sshd-api-core:2.9.2-62.v199162f0a_2f8
    - okhttp-api:4.10.0-132.v7a_7b_91cef39c
    - pipeline-build-step:488.v8993df156e8d
    - pipeline-groovy-lib:656.va_a_ceeb_6ffb_f7
    - pipeline-input-step:466.v6d0a_5df34f81
    - pipeline-milestone-step:111.v449306f708b_7
    - pipeline-model-api:2.2125.vddb_a_44a_d605e
    - pipeline-model-definition:2.2125.vddb_a_44a_d605e
    - pipeline-model-extensions:2.2125.vddb_a_44a_d605e
    - pipeline-stage-step:305.ve96d0205c1c6
    - pipeline-stage-tags-metadata:2.2125.vddb_a_44a_d605e
    - plain-credentials:143.v1b_df8b_d3b_e48
    - scm-api:631.v9143df5b_e4a_a
    - script-security:1244.ve463715a_f89c
    - snakeyaml-api:1.33-95.va_b_a_e3e47b_fa_4
    - ssh-credentials:305.v8f4381501156
    - structs:324.va_f5d6774f3a_d
    - trilead-api:2.84.v72119de229b_7
    - variant:59.vf075fe829ccb
    - workflow-aggregator:590.v6a_d052e5a_a_b_5
    - workflow-api:1208.v0cc7c6e0da_9e
    - workflow-basic-steps:1010.vf7a_b_98e847c1
    - workflow-cps:3659.v582dc37621d8
    - workflow-durable-task-step:1244.vee71f675dee6
    - workflow-job:1289.vd1c337fd5354
    - workflow-multibranch:733.v109046189126
    - workflow-scm-step:408.v7d5b_135a_b_d49
    - workflow-step-api:639.v6eca_cd8c04a_a_
    - workflow-support:839.v35e2736cfd5c
  overwritePlugins: true
  JCasC:
    defaultConfig: true

    configScripts:
      main: |-
        jenkins:
          systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code (JCasC) Plugin.\n\n"
  probes:
    startupProbe:
      periodSeconds: 10
      failureThreshold: 30
    livenessProbe:
      initialDelaySeconds: 60
    readinessProbe:
      initialDelaySeconds: 60

agent:
  enabled: true
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
  alwaysPullImage: true
persistence:
  enabled: true
#  storageClass: "your-storage-class-here"
