apiVersion: v1
kind: Namespace
metadata:
  labels:
    owner: bigbang
  name: bigbang
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: zarf-git-secret
  namespace: bigbang
stringData:
  username: "zarf-git-user"
  password: "###ZARF_GIT_AUTH_PUSH###"
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: zarf-package-software-factory
  namespace: bigbang
spec:
  interval: 1m
  url: $CONFIG_REPO_URL
  secretRef:
    name: zarf-git-secret
  ref:
    branch: feature/gitlab-sso-docs
#    tag: X.Y.Z
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: bigbang
  namespace: bigbang
spec:
  interval: 5m
  path: "./kustomizations/bigbang"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zarf-package-software-factory
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: bigbang
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: cluster-auditor
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: eck-operator
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: ek
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: fluent-bit
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: gatekeeper
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: istio
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: istio-operator
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: jaeger
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: kiali
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: monitoring
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: twistlock
  timeout: 15m
  postBuild:
    substitute:
      ZARF_REGISTRY: "###ZARF_REGISTRY###"
      ZARF_REGISTRY_AUTH_PULL: "###ZARF_REGISTRY_AUTH_PULL###"
