apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: redis-auth
  namespace: flux-system
spec:
  interval: 5m
  path: "./kustomizations/redis-auth"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zarf-package-software-factory
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: softwarefactoryaddons
      name: redis-auth
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute:
      ZARF_REGISTRY: "###ZARF_REGISTRY###"
      ZARF_REGISTRY_AUTH_PULL: "###ZARF_REGISTRY_AUTH_PULL###"
