apiVersion: v1
kind: Namespace
metadata:
  labels:
    owner: bigbang
  name: bigbang
---
apiVersion: v1
kind: Namespace
metadata:
  name: softwarefactoryaddons
  labels:
    istio-injection: enabled
    owner: softwarefactoryaddons
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: bbcore-minio
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: velero-minio
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-minio
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-redis
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: jira
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: confluence
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: artifactory
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: zarf-package-software-factory
  namespace: flux-system
spec:
  interval: 1m
  url: http://zarf-gitea-http.zarf.svc.cluster.local:3000/zarf-git-user/mirror__github.com__defenseunicorns__zarf-package-software-factory.git
  ref:
    branch: not-the-real-branch-name
  #    tag: X.Y.Z
  secretRef:
    name: private-git-server
