apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: zarf-package-software-factory
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/defenseunicorns/zarf-package-software-factory.git
  ref:
    branch: main
#    tag: X.Y.Z
