apiVersion: v1
kind: Namespace
metadata:
  labels:
    owner: bigbang
  name: bigbang
---
apiVersion: v1
kind: Namespace
metadata:
  name: softwarefactoryaddons
  labels:
    istio-injection: disabled
    owner: softwarefactoryaddons
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: jira
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: confluence
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: zarf-package-software-factory
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/defenseunicorns/zarf-package-software-factory.git
  ref:
    branch: feature/update-zarf-and-bigbang-versions
#    tag: X.Y.Z
