apiVersion: v1
kind: Namespace
metadata:
  name: softwarefactoryaddons
  labels:
    istio-injection: disabled
    owner: softwarefactoryaddons
---
apiVersion: v1
kind: Namespace
metadata:
  name: jira
  labels:
    istio-injection: enabled
    owner: softwarefactoryaddons
---
apiVersion: v1
kind: Namespace
metadata:
  name: confluence
  labels:
    istio-injection: enabled
    owner: softwarefactoryaddons
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    istio-injection: enabled
    owner: softwarefactoryaddons
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: zarf-git-secret
  namespace: softwarefactoryaddons
stringData:
  username: "zarf-git-user"
  password: "###ZARF_GIT_AUTH_PUSH###"
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: zarf-package-software-factory
  namespace: softwarefactoryaddons
spec:
  interval: 5m
  url: $CONFIG_REPO_URL
  secretRef:
    name: zarf-git-secret
  ref:
    branch: main
#    tag: X.Y.Z
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: softwarefactoryaddons
  namespace: softwarefactoryaddons
spec:
  interval: 5m
  path: "./kustomizations/softwarefactoryaddons"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zarf-package-software-factory
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: softwarefactoryaddons
      name: jira
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: softwarefactoryaddons
      name: confluence
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: softwarefactoryaddons
      name: jenkins
  timeout: 60m
  postBuild:
    substitute:
      ZARF_REGISTRY: "###ZARF_REGISTRY###"
      ZARF_REGISTRY_AUTH_PULL: "###ZARF_REGISTRY_AUTH_PULL###"
