apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: softwarefactoryaddons
  namespace: flux-system
spec:
  interval: 5m
  path: "./kustomizations/softwarefactoryaddons"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zarf-package-software-factory
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: softwarefactoryaddons
      name: jira
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: softwarefactoryaddons
      name: confluence
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: softwarefactoryaddons
      name: jenkins
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: softwarefactoryaddons
      name: artifactory
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute:
      ZARF_REGISTRY: "###ZARF_REGISTRY###"
      ZARF_REGISTRY_AUTH_PULL: "###ZARF_REGISTRY_AUTH_PULL###"
