apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: redis
  namespace: softwarefactoryaddons
spec:
  interval: 5m
  url: https://repo1.dso.mil/big-bang/product/packages/redis.git
  ref:
    tag: 17.15.4-bb.0
  secretRef:
    name: private-git-server
