apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: redis
  namespace: softwarefactoryaddons
spec:
  interval: 5m
  url: https://repo1.dso.mil/platform-one/big-bang/apps/application-utilities/redis.git
  ref:
    tag: 17.10.2-bb.1
  secretRef:
    name: private-git-server
