resources:
  - base
  - gitlab-secrets.yaml

configMapGenerator:
  - name: redis-common
    namespace: softwarefactoryaddons
    behavior: replace
    files:
      - values.yaml=redis/values.yaml

secretGenerator:
  - name: redis-auth
    namespace: redis
    files:
      - values.yaml=redis-auth/values.yaml

generatorOptions:
  disableNameSuffixHash: true