apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: redis-secret
  namespace: redis
stringData:
  secret: "changemechangeme"
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: redis-secret
  namespace: gitlab
stringData:
  secret: "changemechangeme"

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: gitlab-redis-secret
#   namespace: softwarefactoryaddons
# spec:
#   targetNamespace: redis
#   releaseName: redis-secret
#   interval: 2m
#   timeout: 2m
#   chart:
#     spec:
#       chart: charts/raw
#       sourceRef:
#         kind: GitRepository
#         name: zarf-package-software-factory
#         namespace: flux-system
#   test:
#     enable: false
#   install:
#     remediation:
#       retries: -1
#   upgrade:
#     remediation:
#       retries: 5
#       remediateLastFailure: true
#     cleanupOnFail: true
#   rollback:
#     timeout: 10m
#     cleanupOnFail: false
#   # dependsOn:
#   #   - name: bigbang
#   #     namespace: bigbang
#   valuesFrom:
#     - kind: Secret
#       name: redis-secret
#       valuesKey: values.yaml
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: gitlab-redis-secret-2
#   namespace: softwarefactoryaddons
# spec:
#   targetNamespace: gitlab
#   releaseName: redis-secret
#   interval: 2m
#   timeout: 2m
#   chart:
#     spec:
#       chart: charts/raw
#       sourceRef:
#         kind: GitRepository
#         name: zarf-package-software-factory
#         namespace: flux-system
#   test:
#     enable: false
#   install:
#     remediation:
#       retries: -1
#   upgrade:
#     remediation:
#       retries: 5
#       remediateLastFailure: true
#     cleanupOnFail: true
#   rollback:
#     timeout: 10m
#     cleanupOnFail: false
#   # dependsOn:
#   #   - name: bigbang
#   #     namespace: bigbang
#   valuesFrom:
#     - kind: Secret
#       name: redis-secret
#       valuesKey: values.yaml