configPostgresPodResources:
  default_cpu_request: "100m"
  default_memory_request: "100Mi"
  default_cpu_limit: "500m"
  default_memory_limit: "500Mi"
  min_cpu_limit: "250m"
  min_memory_limit: "250Mi"
# configKubernetes:
#   pod_environment_configmap: "postgres-operator/postgres-pod-config"
configConnectionPooler:
  connection_pooler_default_cpu_request: "100m"
  connection_pooler_default_cpu_limit: "500m"
  connection_pooler_default_memory_request: "100Mi"
  connection_pooler_default_memory_limit: "100Mi"
resources:
  requests:
    cpu: "100m"
    memory: "250Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"
securityContext:
  runAsUser: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
