# nonk8s
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: artifactory-database
  namespace: softwarefactoryaddons
spec:
  targetNamespace: artifactory
  releaseName: artifactory-database
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: charts/raw
      sourceRef:
        kind: GitRepository
        name: zarf-package-software-factory
        namespace: flux-system
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  dependsOn:
    - name: bigbang
      namespace: bigbang
    - name: postgres-operator
      namespace: softwarefactoryaddons
    - name: kyvernopolicies
      namespace: bigbang
    - name: istio
      namespace: bigbang
    - name: postgres-minio
      namespace: bigbang
  values:
    resources:
    - apiVersion: "acid.zalan.do/v1"
      kind: "postgresql"
      metadata:
        name: "acid-artifactory"
        namespace: "artifactory"
      spec:
        teamId: "acid"
        postgresql:
          version: "13"
        numberOfInstances: 3
        volume:
          size: "2Gi"
          # Uncomment this if you want to specify a particular storage class
      #    storageClass: "your-storage-class-name-here"
        env:
        - name: BACKUP_SCHEDULE
          value: '00 00 * * *'
        - name: AWS_S3_FORCE_PATH_STYLE
          value: "true" # needed for MinIO
        - name: AWS_ENDPOINT
          value: http://minio.postgres-minio.svc.cluster.local:80
        - name: BACKUP_NUM_TO_RETAIN
          value: "7"
        - name: USE_WALG_BACKUP
          value: "true"
        - name: USE_WALG_RESTORE
          value: "true"
        - name: WALG_DISABLE_S3_SSE
          value: "true"
        - name: AWS_REGION
          value: minio
        # Clone Section
        - name: CLONE_AWS_S3_FORCE_PATH_STYLE
          value: "true" # needed for MinIO
        - name: CLONE_AWS_ENDPOINT
          value: http://minio.postgres-minio.svc.cluster.local:80
        - name: CLONE_USE_WALG_RESTORE
          value: "true"
        - name: CLONE_WALG_DISABLE_S3_SSE
          value: "true"
        - name: CLONE_AWS_REGION
          value: minio
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: "1"
            memory: "2Gi"
