apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: jira
  namespace: softwarefactoryaddons
spec:
  interval: 5m
  url: http://zarf-gitea-http.zarf.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__third-party__jira.git
  ref:
    tag: 1.4.1-bb.0
  secretRef:
    name: private-git-server
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: confluence
  namespace: softwarefactoryaddons
spec:
  interval: 5m
  url: http://zarf-gitea-http.zarf.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__third-party__confluence.git
  ref:
    tag: 0.1.0-bb.20
  secretRef:
    name: private-git-server
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: jenkins
  namespace: softwarefactoryaddons
spec:
  interval: 5m
  url: http://zarf-gitea-http.zarf.svc.cluster.local:3000/zarf-git-user/mirror__github.com__jenkinsci__helm-charts.git
  ref:
    tag: jenkins-3.9.4
  secretRef:
    name: private-git-server
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: artifactory
  namespace: softwarefactoryaddons
spec:
  interval: 5m
  url: http://zarf-gitea-http.zarf.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__third-party__artifactory.git
  ref:
    tag: 0.9.2
  secretRef:
    name: private-git-server
