apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: jira
  namespace: softwarefactoryaddons
spec:
  interval: 5m
  url: https://repo1.dso.mil/platform-one/big-bang/apps/third-party/jira.git
  ref:
    tag: 1.6.0-bb.2
  secretRef:
    name: private-git-server
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: confluence
  namespace: softwarefactoryaddons
spec:
  interval: 5m
  url: https://repo1.dso.mil/platform-one/big-bang/apps/third-party/confluence.git
  ref:
    tag: 0.1.0-bb.20
  secretRef:
    name: private-git-server
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: jenkins
  namespace: softwarefactoryaddons
spec:
  interval: 5m
  url: https://github.com/jenkinsci/helm-charts.git
  ref:
    tag: jenkins-4.1.12
  secretRef:
    name: private-git-server
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: artifactory
  namespace: softwarefactoryaddons
spec:
  interval: 5m
  url: https://repo1.dso.mil/platform-one/big-bang/apps/third-party/artifactory.git
  ref:
    tag: 0.9.2
  secretRef:
    name: private-git-server
