apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jira
  namespace: softwarefactoryaddons
spec:
  targetNamespace: jira
  releaseName: jira
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: jira
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  valuesFrom:
    - kind: Secret
      name: jira-common-bb
      valuesKey: values.yaml
    - kind: ConfigMap
      name: jira-common
      valuesKey: values.yaml
    - kind: Secret
      name: jira-environment-bb
      valuesKey: values.yaml
    - kind: ConfigMap
      name: jira-environment
      valuesKey: values.yaml
  dependsOn:
    - name: istio
      namespace: bigbang
    - name: jira-database
      namespace: softwarefactoryaddons
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluence
  namespace: softwarefactoryaddons
spec:
  targetNamespace: confluence
  releaseName: confluence
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: confluence
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  valuesFrom:
    - kind: Secret
      name: confluence-common-bb
      valuesKey: values.yaml
    - kind: ConfigMap
      name: confluence-common
      valuesKey: values.yaml
    - kind: Secret
      name: confluence-environment-bb
      valuesKey: values.yaml
    - kind: ConfigMap
      name: confluence-environment
      valuesKey: values.yaml
  dependsOn:
    - name: istio
      namespace: bigbang
    - name: confluence-database
      namespace: softwarefactoryaddons
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: softwarefactoryaddons
spec:
  targetNamespace: jenkins
  releaseName: jenkins
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: charts/jenkins
      sourceRef:
        kind: GitRepository
        name: jenkins
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  valuesFrom:
    - kind: Secret
      name: jenkins-common-bb
      valuesKey: values.yaml
    - kind: ConfigMap
      name: jenkins-common
      valuesKey: values.yaml
    - kind: Secret
      name: jenkins-environment-bb
      valuesKey: values.yaml
    - kind: ConfigMap
      name: jenkins-environment
      valuesKey: values.yaml
  dependsOn:
    - name: istio
      namespace: bigbang
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: artifactory
  namespace: softwarefactoryaddons
spec:
  targetNamespace: artifactory
  releaseName: artifactory
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: "."
      sourceRef:
        kind: GitRepository
        name: artifactory
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  valuesFrom:
    - kind: Secret
      name: artifactory-common-bb
      valuesKey: values.yaml
    - kind: ConfigMap
      name: artifactory-common
      valuesKey: values.yaml
    - kind: Secret
      name: artifactory-environment-bb
      valuesKey: values.yaml
    - kind: ConfigMap
      name: artifactory-environment
      valuesKey: values.yaml
  dependsOn:
    - name: istio
      namespace: bigbang
    - name: artifactory-database
      namespace: softwarefactoryaddons
---
# nonk8s
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: artifactory-database
  namespace: softwarefactoryaddons
spec:
  targetNamespace: artifactory
  releaseName: artifactory-database
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: charts/raw
      sourceRef:
        kind: GitRepository
        name: zarf-package-software-factory
        namespace: flux-system
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  dependsOn:
    - name: bigbang
      namespace: bigbang
    - name: postgres-operator
      namespace: softwarefactoryaddons
    - name: kyvernopolicies
      namespace: bigbang
    - name: istio
      namespace: bigbang
    - name: postgres-minio
      namespace: bigbang
  values:
    resources:
    - apiVersion: "acid.zalan.do/v1"
      kind: "postgresql"
      metadata:
        name: "acid-artifactory"
        namespace: "artifactory"
      spec:
        teamId: "acid"
        postgresql:
          version: "13"
        numberOfInstances: 3
        volume:
          size: "2Gi"
          # Uncomment this if you want to specify a particular storage class
      #    storageClass: "your-storage-class-name-here"
        env:
        - name: WAL_S3_BUCKET
          value: ""
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: "1"
            memory: "2Gi"
---
# nonk8s
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluence-database
  namespace: softwarefactoryaddons
spec:
  targetNamespace: confluence
  releaseName: confluence-database
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: charts/raw
      sourceRef:
        kind: GitRepository
        name: zarf-package-software-factory
        namespace: flux-system
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  dependsOn:
    - name: bigbang
      namespace: bigbang
    - name: postgres-operator
      namespace: softwarefactoryaddons
    - name: kyvernopolicies
      namespace: bigbang
    - name: istio
      namespace: bigbang
    - name: postgres-minio
      namespace: bigbang
  values:
    resources:
    - apiVersion: "acid.zalan.do/v1"
      kind: "postgresql"
      metadata:
        name: "acid-confluence"
        namespace: "confluence"
      spec:
        teamId: "acid"
        postgresql:
          version: "13"
        numberOfInstances: 3
        volume:
          size: "2Gi"
          # Uncomment this if you want to specify a particular storage class
      #    storageClass: "your-storage-class-name-here"
        users:
          # role for confluence application
          confluence: []
        databases:
          confluence: confluence
        env:
        - name: WAL_S3_BUCKET
          value: ""
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: "1"
            memory: 2000Mi
---
# nonk8s
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jira-database
  namespace: softwarefactoryaddons
spec:
  targetNamespace: jira
  releaseName: jira-database
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: charts/raw
      sourceRef:
        kind: GitRepository
        name: zarf-package-software-factory
        namespace: flux-system
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  dependsOn:
    - name: bigbang
      namespace: bigbang
    - name: postgres-operator
      namespace: softwarefactoryaddons
    - name: kyvernopolicies
      namespace: bigbang
    - name: istio
      namespace: bigbang
    - name: postgres-minio
      namespace: bigbang
  values:
    resources:
    - apiVersion: "acid.zalan.do/v1"
      kind: "postgresql"
      metadata:
        name: "acid-jira"
        namespace: "jira"
      spec:
        teamId: "acid"
        postgresql:
          version: "11"
        numberOfInstances: 3
        volume:
          size: "2Gi"
          # Uncomment this if you want to specify a particular storage class
      #    storageClass: "your-storage-class-name-here"
        users:
          jira: []
        databases:
          jira: jira
        env:
        - name: BACKUP_SCHEDULE
          value: '00 00 * * *'
        - name: AWS_S3_FORCE_PATH_STYLE
          value: "true" # needed for MinIO
        - name: AWS_ENDPOINT
          value: http://minio.postgres-minio.svc.cluster.local:80
        - name: BACKUP_NUM_TO_RETAIN
          value: "7"
        - name: USE_WALG_BACKUP
          value: "true"
        - name: USE_WALG_RESTORE
          value: "true"
        - name: CLONE_USE_WALG_RESTORE
          value: "true"
        - name: WALG_DISABLE_S3_SSE
          value: "true"
        - name: AWS_REGION
          value: minio
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: "1"
            memory: 2000Mi
