configurations:
  - transformer.yaml

commonLabels:
  owner: softwarefactoryaddons

resources:
  - serviceaccount.yaml
  - gitrepository.yaml
  - helmrelease.yaml
  - postgresql.yaml
  - virtualservice.yaml

configMapGenerator:
  - name: jira-common
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: jira-environment
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: confluence-common
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: confluence-environment
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: jenkins-common
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: jenkins-environment
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: artifactory-common
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: artifactory-environment
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=

# Flux combines secrets and configmaps in `valuesFrom`.  Kustomize
# cannot distinguish between them when applying suffixes.  Therefore,
# the secrets must have different names than the configmaps
# While capital letters or dashes could be used, '-bb' was chosen
# to make the difference obvious at a glance
secretGenerator:
  - name: jira-common-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: jira-environment-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: confluence-common-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: confluence-environment-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: jenkins-common-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: jenkins-environment-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: artifactory-common-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
  - name: artifactory-environment-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - values.yaml=
