configurations:
- transformer.yaml

commonLabels:
  owner: softwarefactoryaddons

resources:
  - namespace.yaml
  - gitrepository.yaml
  - helmrelease.yaml
  - virtualservice.yaml

configMapGenerator:
  - name: jira-common
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - jira-common-values.yaml=
  - name: jira-environment
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - jira-environment-values.yaml=
  - name: confluence-common
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - confluence-common-values.yaml=
  - name: confluence-environment
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - confluence-environment-values.yaml=
  - name: jenkins-common
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - jenkins-common-values.yaml=
  - name: jenkins-environment
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - jenkins-environment-values.yaml=

# Flux combines secrets and configmaps in `valuesFrom`.  Kustomize
# cannot distinguish between them when applying suffixes.  Therefore,
# the secrets must have different names than the configmaps
# While capital letters or dashes could be used, '-bb' was chosen
# to make the difference obvious at a glance
secretGenerator:
  - name: jira-common-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - jira-common-bb-values.yaml=
  - name: jira-environment-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - jira-environment-bb-values.yaml=
  - name: confluence-common-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - confluence-common-bb-values.yaml=
  - name: confluence-environment-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - confluence-environment-bb-values.yaml=
  - name: jenkins-common-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - jenkins-common-bb-values.yaml=
  - name: jenkins-environment-bb
    namespace: softwarefactoryaddons
    behavior: create
    literals:
      - jenkins-environment-bb-values.yaml=