# nonk8s
apiVersion: "acid.zalan.do/v1"
kind: "postgresql"
metadata:
  name: "acid-confluence"
  namespace: "confluence"
spec:
  teamId: "acid"
  postgresql:
    version: "13"
  numberOfInstances: 3
  volume:
    size: "2Gi"
    # Uncomment this if you want to specify a particular storage class
#    storageClass: "your-storage-class-name-here"
  users:
    # role for confluence application
    confluence: []
  databases:
    confluence: confluence
  # enableLogicalBackup: true
  # logicalBackupSchedule: "*/2 * * * *"
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: "1"
      memory: 2000Mi
---
apiVersion: "acid.zalan.do/v1"
kind: "postgresql"
metadata:
  name: "acid-jira"
  namespace: "jira"
spec:
  teamId: "acid"
  postgresql:
    version: "11"
  numberOfInstances: 3
  volume:
    size: "2Gi"
    # Uncomment this if you want to specify a particular storage class
#    storageClass: "your-storage-class-name-here"
  users:
    jira: []
  databases:
    jira: jira
  # enableLogicalBackup: true
  # logicalBackupSchedule: "*/2 * * * *"
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: "1"
      memory: 2000Mi
---
apiVersion: "acid.zalan.do/v1"
kind: "postgresql"
metadata:
  name: "acid-artifactory"
  namespace: "artifactory"
spec:
  teamId: "acid"
  postgresql:
    version: "13"
  numberOfInstances: 3
  volume:
    size: "2Gi"
    # Uncomment this if you want to specify a particular storage class
#    storageClass: "your-storage-class-name-here"
  # enableLogicalBackup: true
  # logicalBackupSchedule: "*/2 * * * *"
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: "1"
      memory: "2Gi"
