image:
  registry: "${ZARF_REGISTRY}"
  repository: acid/postgres-operator
imagePullSecrets:
  - name: private-registry
configGeneral:
  docker_image: "${ZARF_REGISTRY}/acid/spilo-13:2.1-p1"
configPostgresPodResources:
  default_cpu_request: "100m"
  default_memory_request: "100Mi"
  default_cpu_limit: "500m"
  default_memory_limit: "500Mi"
  min_cpu_limit: "250m"
  min_memory_limit: "250Mi"
# configKubernetes:
#   pod_environment_configmap: "postgres-operator/postgres-pod-config"
configLogicalBackup:
  logical_backup_docker_image: "${ZARF_REGISTRY}/acid/logical-backup:v1.7.0"
configConnectionPooler:
  connection_pooler_image: "${ZARF_REGISTRY}/acid/pgbouncer:master-18"
  connection_pooler_default_cpu_request: "100m"
  connection_pooler_default_cpu_limit: "500m"
  connection_pooler_default_memory_request: "100Mi"
  connection_pooler_default_memory_limit: "100Mi"
resources:
  requests:
    cpu: "100m"
    memory: "250Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"
securityContext:
  runAsUser: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
