resources:
  - vendor/bigbang/base

secretGenerator:
  - name: common-bb
    namespace: bigbang
    behavior: merge
    files:
      - common-bb/values.yaml
  - name: environment-bb
    namespace: bigbang
    behavior: merge
    files:
      - environment-bb/values.yaml

patchesStrategicMerge:
  - |-
    apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    metadata:
      name: bigbang
      namespace: bigbang
    spec:
      url: http://zarf-gitea-http.zarf.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__bigbang.git
      secretRef:
        name: zarf-git-secret
