apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minio-operator-egress
  namespace: gitlab
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: minioOperator
      ports:
        - port: 4222
          protocol: TCP
