apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bbcore-minio
  namespace: bigbang
spec:
  targetNamespace: bbcore-minio
  releaseName: bbcore-minio
  interval: 2m
  timeout: 2m
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: minio
        namespace: bigbang
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  dependsOn:
    - name: bigbang
      namespace: bigbang
    - name: istio
      namespace: bigbang
    - name: gatekeeper
      namespace: bigbang
    - name: minio-operator
      namespace: bigbang
  valuesFrom:
    - kind: ConfigMap
      name: common-minio-common
      valuesKey: values.yaml
    - kind: ConfigMap
      name: common-bbcore-minio
    - kind: Secret
      name: environment-bb-minio-common
      valuesKey: values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-minio
  namespace: bigbang
spec:
  targetNamespace: gitlab-minio
  releaseName: gitlab-minio
  interval: 2m
  timeout: 2m
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: minio
        namespace: bigbang
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  dependsOn:
    - name: bigbang
      namespace: bigbang
    - name: istio
      namespace: bigbang
    - name: gatekeeper
      namespace: bigbang
    - name: minio-operator
      namespace: bigbang
  valuesFrom:
    - kind: ConfigMap
      name: common-minio-common
      valuesKey: values.yaml
    - kind: ConfigMap
      name: common-gitlab-minio
    - kind: Secret
      name: environment-bb-minio-common
      valuesKey: values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero-minio
  namespace: bigbang
spec:
  targetNamespace: velero-minio
  releaseName: velero-minio
  interval: 2m
  timeout: 2m
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: minio
        namespace: bigbang
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  dependsOn:
    - name: bigbang
      namespace: bigbang
    - name: istio
      namespace: bigbang
    - name: gatekeeper
      namespace: bigbang
    - name: minio-operator
      namespace: bigbang
  valuesFrom:
    - kind: ConfigMap
      name: common-minio-common
      valuesKey: values.yaml
    - kind: ConfigMap
      name: common-velero-minio
    - kind: Secret
      name: environment-bb-minio-common
      valuesKey: values.yaml
