apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-minio
  namespace: bigbang
spec:
  targetNamespace: gitlab
  releaseName: gitlab-minio
  interval: 2m
  timeout: 2m
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: minio-tenant-chart
        namespace: flux-system
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  dependsOn:
    - name: bigbang
      namespace: bigbang
    - name: minio-operator
      namespace: bigbang
    - name: gatekeeper
      namespace: bigbang
  valuesFrom:
    - kind: ConfigMap
      name: common-gitlab-minio
      valuesKey: values.yaml
    - kind: Secret
      name: environment-bb-gitlab-minio
      valuesKey: values.yaml
