apiVersion: v1
kind: Namespace
metadata:
  name: helm-install-jenkins
labels:
    istio-injection: "disabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
labels:
    istio-injection: "enabled"
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: private-registry
  namespace: jenkins
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.dso.mil": {
          "auth":"###ZARF_DOCKERAUTH###"
        },
        "registry1.dso.mil": {
          "auth":"###ZARF_DOCKERAUTH###"
        },
        "docker.io": {
          "auth":"###ZARF_DOCKERAUTH###"
        },
        "registry-1.docker.io": {
          "auth":"###ZARF_DOCKERAUTH###"
        },
        "ghcr.io": {
          "auth":"###ZARF_DOCKERAUTH###"
        }
      }
    }
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: jenkins
  namespace: helm-install-jenkins
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/jenkins-3.9.4.tgz
  targetNamespace: jenkins
  valuesContent: |-
    controller:
      image: "jenkins/jenkins"
      tag: "2.319.1-jdk11"
      imagePullSecretName: "private-registry"
      adminUser: "admin"
      adminPassword: "admin"
      resources:
        requests:
          cpu: "50m"
          memory: "256Mi"
        limits:
          cpu: "2000m"
          memory: "4096Mi"
      initContainerResources:
        requests:
          cpu: "50m"
          memory: "256Mi"
        limits:
          cpu: "2000m"
          memory: "4096Mi"
      installPlugins:
        - kubernetes:1.31.1
        - workflow-aggregator:2.6
        - git:4.10.1
        - configuration-as-code:1.55
      jenkinsUrlProtocol: "https"
      jenkinsUrl: "jenkins.bigbang.dev:9443"
    agent:
      enabled: true
      image: "jenkins/inbound-agent"
      tag: "4.11-1"
      imagePullSecretName: "private-registry"
      resources:
        requests:
          cpu: "512m"
          memory: "512Mi"
        limits:
          cpu: "512m"
          memory: "512Mi"
      alwaysPullImage: true
    persistence:
      enabled: true
      storageClass: "local-path"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jenkins
  namespace: jenkins
spec:
  gateways:
    - istio-system/public
  hosts:
    - jenkins.bigbang.dev
  http:
    - route:
        - destination:
            host: jenkins.jenkins.svc.cluster.local
            port:
              number: 8080
