# Helm chart version:
global:
  imageRegistry: registry1.dso.mil
  artifactoryHaEnabled: false
  database:
    host: "acid-artifactory.artifactory.svc.cluster.local"
    port: 5432
    sslMode: "require"
    adminUsername: "postgres"
    secrets:
      adminPassword:
        name: "postgres.acid-artifactory.credentials.postgresql.acid.zalan.do"
        key: "password"
    initContainerSetupDBImage: registry1.dso.mil/ironbank/opensource/postgres/postgresql:13.10
    initDBCreation: true
rabbitmq:
  enabled: false
redis:
  enabled: false
artifactory:
  enabled: true
  nginx:
    enabled: false
  # Uncomment if you want to specify a particular storage class
#  artifactory:
#    persistence:
#      storageClassName: "your-storage-class-here"
postgresql:
  enabled: false
artifactory-ha:
  enabled: false
xray:
  enabled: false
distribution:
  enabled: false
mission-control:
  enabled: false
pipelines:
  enabled: false
