# Helm chart version:
global:
  imageRegistry: registry1.dso.mil
  artifactoryHaEnabled: false
  database:
    host: "acid-artifactory.artifactory.svc.cluster.local"
    port: 5432
    sslMode: "require"
    adminUsername: "postgres"
    secrets:
      adminPassword:
        name: "postgres.acid-artifactory.credentials.postgresql.acid.zalan.do"
        key: "password"
    initContainerSetupDBImage: registry1.dso.mil/ironbank/opensource/postgres/postgresql:13.10
    initContainerSetupDBUser: 0
    initDBCreation: true
rabbitmq:
  enabled: false
redis:
  enabled: false
artifactory:
  enabled: true
  initContainerImage: registry1.dso.mil/ironbank/redhat/ubi/ubi9-minimal:9.1.0
  artifactory:
    image:
      registry: registry1.dso.mil
      repository: ironbank/jfrog/artifactory/artifactory
      tag: 7.55.9
    # Uncomment if you want to specify a particular storage class
    # persistence:
    #   storageClassName: "your-storage-class-here"
  nginx:
    enabled: false
postgresql:
  enabled: false
artifactory-ha:
  enabled: false
xray:
  enabled: false
distribution:
  enabled: false
insight:
  enabled: false
pipelines:
  enabled: false
pdnServer:
  enabled: false
