apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-shared-home-single-node
  namespace: confluence
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
