apiVersion: "acid.zalan.do/v1"
kind: "postgresql"
metadata:
  name: "acid-gitlab"
  namespace: "gitlab"
spec:
  teamId: "acid"
  postgresql:
    version: "13"
  numberOfInstances: 3
  volume:
    size: "2Gi"
  users:
    # role for gitlab application
    gitlab: []
  databases:
    gitlabhq_production: gitlab
  # enableLogicalBackup: true
  # logicalBackupSchedule: "*/2 * * * *"
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "1"
      memory: "2Gi"
