resources:
  - base

configMapGenerator:
  - name: postgres-operator-common
    namespace: softwarefactoryaddons
    behavior: replace
    files:
      - values.yaml=postgres-operator/common-values.yaml

secretGenerator:
  - name: postgres-operator-environment-bb
    namespace: softwarefactoryaddons
    behavior: replace
    files:
      - values.yaml=postgres-operator/environment-bb-values.yaml
