apiVersion: v1
kind: Pod
metadata:
  name: backup-restore-tools
  namespace: jenkins
spec:
  containers:
  - name: toolbox
    image: registry1.dso.mil/ironbank/big-bang/base:2.0.0
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: jenkins-home
      mountPath: /tmp/jenkins-home
    securityContext:
      runAsUser: 1000
  volumes:
  - name: jenkins-home
    persistentVolumeClaim:
      claimName: jenkins
