# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/zarf/v0.26.3/zarf.schema.json
kind: ZarfPackageConfig
metadata:
  name: "flux"
  description: "Zarf flux package"
  architecture: amd64

components:
  - name: flux
    required: true
    manifests:
      - name: flux-installer
        # This will be built on the package create side and deployed as a regular manifest on package deploy
        kustomizations:
          - https://repo1.dso.mil/platform-one/big-bang/bigbang.git/base/flux?ref=2.2.0
    images:
      # flux - flux
      - registry1.dso.mil/ironbank/fluxcd/source-controller:v0.36.1
      - registry1.dso.mil/ironbank/fluxcd/helm-controller:v0.32.1
      - registry1.dso.mil/ironbank/fluxcd/kustomize-controller:v0.35.1
      - registry1.dso.mil/ironbank/fluxcd/notification-controller:v0.33.0
