kind: ZarfPackageConfig
metadata:
  name: "flux"
  description: "Zarf flux package"
  architecture: amd64

components:
  - name: flux
    required: true
    manifests:
      - name: flux-installer
        # This will be built on the package create side and deployed as a regular manifest on package deploy
        kustomizations:
          - https://repo1.dso.mil/platform-one/big-bang/bigbang.git/base/flux?ref=1.43.0
    images:
      # flux - flux
      - registry1.dso.mil/ironbank/fluxcd/helm-controller:v0.22.2
      - registry1.dso.mil/ironbank/fluxcd/kustomize-controller:v0.27.0
      - registry1.dso.mil/ironbank/fluxcd/notification-controller:v0.25.1
      - registry1.dso.mil/ironbank/fluxcd/source-controller:v0.26.1
