apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: softwarefactoryaddons
spec:
  targetNamespace: longhorn-system
  releaseName: longhorn
  interval: 5m
  timeout: 10m
  chart:
    spec:
      interval: 1m
      chart: chart
      sourceRef:
        kind: GitRepository
        name: longhorn
  dependsOn:
    - name: istio
      namespace: bigbang
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 30m
    cleanupOnFail: false
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-common
      valuesKey: values.yaml
