controller:
  image: "${ZARF_REGISTRY}/jenkins/jenkins"
  tag: "2.319.1-jdk11"
  imagePullSecretName: "private-registry"
  #  adminUser: "admin"
  #  adminPassword: "admin"
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  initContainerResources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  installPlugins:
    # Top level plugins
    - kubernetes:3580.v78271e5631dc
    - workflow-aggregator:2.7
    - git:4.11.0
    - configuration-as-code:1414.v878271fc496f
    - gitlab-oauth:1.15
    # Dependencies of the top level plugins. They need to be specified explicitly or the top level plugins
    # will try to grab the latest versions of them, which will break other dependency trees. It sucks
    # to have to maintain this list, but it is the only way that this author knows for how to make
    # consistently repeatable Jenkins deployments. This list is logged in the Jenkins init container
    # when Jenkins starts up. The list below needs to be updated when ever the list of top level plugins
    # changes. To update it, delete the list below, run the deployment, and get the new list of all
    # plugins from the init container logs.
    # To fix the formatting:
    # Use this find regex:           - (?<name>.*?) (?<version>.*?)$
    # And this replace regex:        - ${name}:${version}

  overwritePlugins: true
  jenkinsUrlProtocol: "https"
  jenkinsUrl: "jenkins.bigbang.dev"
  sidecars:
    configAutoReload:
      image: "${ZARF_REGISTRY}/kiwigrid/k8s-sidecar:1.14.2"
  JCasC:
    jenkins:
      systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code (JCasC) Plugin.\n\n"
      securityRealm:
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
            - id: "admin"
              name: "Jenkins Admin"
              password: "admin"
              properties:
                - "apiToken"
                - "mailer"
                - "myView"
                - preferredProvider:
                    providerId: "default"
                - "timezone"
      agentProtocols:
        - "JNLP4-connect"
        - "Ping"
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      clouds:
        - kubernetes:
            containerCap: 10
            containerCapStr: "10"
            jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
            jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
            name: "kubernetes"
            namespace: "jenkins"
            podLabels:
              - key: "jenkins/jenkins-jenkins-agent"
                value: "true"
            serverUrl: "https://kubernetes.default"
            templates:
              - containers:
                  - alwaysPullImage: true
                    args: "^$${computer.jnlpmac} ^$${computer.name}"
                    envVars:
                      - envVar:
                          key: "JENKINS_URL"
                          value: "http://jenkins.jenkins.svc.cluster.local:8080/"
                    image: "127.0.0.1:31999/jenkins/inbound-agent:4.11-1"
                    name: "jnlp"
                    resourceLimitCpu: "512m"
                    resourceLimitMemory: "512Mi"
                    resourceRequestCpu: "512m"
                    resourceRequestMemory: "512Mi"
                    workingDir: "/home/jenkins/agent"
                # id: "6549f2da428c0fc7ea219f48f8bb193b210bf3b2950ce33a4c85fd85636fcb45"
                imagePullSecrets:
                  - name: "private-registry"
                label: "jenkins-jenkins-agent"
                name: "default"
                nodeUsageMode: "NORMAL"
                podRetention: "never"
                serviceAccount: "default"
                slaveConnectTimeout: 100
                slaveConnectTimeoutStr: "100"
                yamlMergeStrategy: "override"
      crumbIssuer:
        standard:
          excludeClientIPFromCrumb: true
      disableRememberMe: false
      labelAtoms:
        - name: "built-in"
        - name: "jenkins-jenkins-agent"
      markupFormatter: "plainText"
      mode: NORMAL
      myViewsTabBar: "standard"
      numExecutors: 0
      primaryView:
        all:
          name: "all"
      projectNamingStrategy: "standard"
      quietPeriod: 5
      remotingSecurity:
        enabled: true
      scmCheckoutRetryCount: 0
      slaveAgentPort: 50000
      updateCenter:
        sites:
          - id: "default"
            url: "https://updates.jenkins.io/update-center.json"
      views:
        - all:
            name: "all"
      viewsTabBar: "standard"
    globalCredentialsConfiguration:
      configuration:
        providerFilter: "none"
        typeFilter: "none"
    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
      sSHD:
        port: -1
    unclassified:
      buildDiscarders:
        configuredBuildDiscarders:
          - "jobBuildDiscarder"
      fingerprints:
        fingerprintCleanupDisabled: false
        storage: "file"
      gitSCM:
        addGitTagAction: false
        allowSecondFetch: false
        createAccountBasedOnEmail: false
        disableGitToolChooser: false
        hideCredentials: false
        showEntireCommitSummaryInChanges: false
        useExistingAccountWithSameEmail: false
      junitTestResultStorage:
        storage: "file"
      location:
        adminAddress: "Software Factory Admin <admin@example.com>"
      mailer:
        charset: "UTF-8"
        useSsl: false
        useTls: false
      pollSCM:
        pollingThreadCount: 10
    tool:
      git:
        installations:
          - home: "git"
            name: "Default"
      mavenGlobalConfig:
        globalSettingsProvider: "standard"
        settingsProvider: "standard"
agent:
  enabled: true
  image: "${ZARF_REGISTRY}/jenkins/inbound-agent"
  tag: "4.11-1"
  imagePullSecretName: "private-registry"
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
  alwaysPullImage: true
persistence:
  enabled: true
  storageClass: "local-path"
