resources:
  - base

configMapGenerator:
  - name: jira-common
    namespace: softwarefactoryaddons
    behavior: replace
    files:
      - values.yaml=jira/values.yaml
  - name: jenkins-common
    namespace: softwarefactoryaddons
    behavior: replace
    files:
      - values.yaml=jenkins/common-values.yaml
  - name: confluence-common
    namespace: softwarefactoryaddons
    behavior: replace
    files:
      - values.yaml=confluence/common-values.yaml
  - name: artifactory-common
    namespace: softwarefactoryaddons
    behavior: replace
    files:
      - values.yaml=artifactory/common-values.yaml

secretGenerator:
  - name: confluence-environment-bb
    namespace: softwarefactoryaddons
    behavior: replace
    files:
      - values.yaml=confluence/environment-bb-values.yaml
  - name: jenkins-environment-bb
    namespace: softwarefactoryaddons
    behavior: replace
    files:
      - values.yaml=jenkins/environment-bb-values.yaml
  - name: artifactory-environment-bb
    namespace: softwarefactoryaddons
    behavior: replace
    files:
      - values.yaml=artifactory/environment-bb-values.yaml
